### PR TITLE
More aggressive fallback to macintosh names

### LINKED ISSUE #47: Optima.ttc works only when using full names but not / shorthands
Trying to use Optima (.ttc) on OSX but it doesn't seem to find the Bold or Italic etc if the `/` notation is used with LuaTeX, eg

~~~~
\documentclass{article}

\begin{document}
\font\1="Optima" at 12pt\relax
\1\fontname\1

\font\2="Optima/I" at 12pt\relax
\2\fontname\2

\font\3="Optima Italic" at 12pt\relax
\3\fontname\3

\font\2="Palatino" at 12pt\relax
\2\fontname\2

\font\3="Palatino/I" at 12pt\relax
\3\fontname\3

\font\4="Palatino Italic" at 12pt\relax
\4\fontname\4
\end{document}
~~~~

It works correctly with the long names. For Palatino it works in both forms. And it does work correctly when XeTeX is used.

The entries in the names.lua.gz look about the same, so I have clue why it fails for Optima:

~~~~
  {
   ["basename"]="Optima.ttc",
   ["conflicts"]={
    ["barename"]=2142,
    ["basename"]=2142,
   },
   ["fontname"]="optimaitalic",
   ["format"]="ttc",
   ["fullname"]="optimaitalic",
   ["fullpath"]="/System/Library/Fonts/Optima.ttc",
   ["index"]=2144,
   ["italicangle"]=-12,
   ["location"]="system",
   ["pfmweight"]=400,
   ["plainname"]="Optima Italic",
   ["size"]=false,
   ["subfamily"]="italic",
   ["subfont"]=3,
   ["version"]="13.0d1e2",
   ["weight"]="normal",
   ["width"]=5,
  },
~~~~
~~~~
   ["basename"]="Palatino.ttc",
   ["conflicts"]={
    ["barename"]=2249,
    ["basename"]=2249,
   },
   ["familyname"]="palatino",
   ["fontname"]="palatinoitalic",
   ["format"]="ttc",
   ["fullname"]="palatinoitalic",
   ["fullpath"]="/System/Library/Fonts/Palatino.ttc",
   ["index"]=2250,
   ["italicangle"]=-12,
   ["location"]="system",
   ["pfmweight"]=400,
   ["plainname"]="Palatino Italic",
   ["psname"]="palatinoitalic",
   ["size"]=false,
   ["subfamily"]="italic",
   ["subfont"]=2,
   ["version"]="13.0d1e2",
   ["weight"]="normal",
   ["width"]=5,
  },
~~~~
The only difference that I can see is that the "familyname" is missing in the optima entry. Maybe that's the reason, but I have no idea why that is not set. Might be related to https://github.com/lualatex/luaotfload/issues/392

### PR DESCRIPTION
**Pull request by zauguin**
Fixes #47.

### CODE REVIEW

**Comment by u-fischer** [comment]
@zauguin  Thanks, I will ask Frank to test (I can't ...). 

Do you think it would be possible to create tests for such lookups without the actual fonts? E.g. that one write a  mac-names.lua, and in some document has a function "lookup_font("name:optima/b:mode=node;","mac-names.lua") which returns the info about font it would use without actually loading the font?

**Comment by zauguin** [comment]
@u-fischer I think it would be best to create a test font which shows the behaviour in question.
I created a test with such a font in [a gist](https://gist.github.com/zauguin/213be692a14a7b96a2f302459ca1d18a), but I am not sure where to place the font file for the test to find them: It is a name lookup, so they have to be in the texmf or the system font directory. So maybe in `texmf`, but it should only be visible during the tests.

**Comment by u-fischer** [comment]
Adding dummy fonts is a good idea. It should be unproblematic - they can go in the texmf. I'm just trying out if it works on travis as expected.  

But the concrete test fails for me on windows: \font\testfamily={Dummy Font Family/B}\testfamily can not be resolved.

**Comment by zauguin** [comment]
@u-fischer But you did use the patched version of luaotfload, right? Have you tried rebuilding the font cache? This is only supposed to happen when the font was added to the fontcache by an unpatched luaotfload version...
Which reminds me, we should trigger a database update here.

**Comment by u-fischer** [comment]
It works now. Not quite sure what went wrong previously, I think I mixed up two log-files.

**Comment by u-fischer** [comment]
this has been imported in version 2.97

**Pull request closed without merging**
