### PR TITLE
Don't replicate datatables from the fontloader

### PR DESCRIPTION
**Pull request by zauguin**
Delete copies from tables also present in the fontloader, especially unused ones.

### CODE REVIEW

**Comment by u-fischer** [comment]
looks good. I will merge and test when I'm home again.

**Comment by u-fischer** [comment]
@zauguin  I just saw that this gives a problem with luaotfload-tool. With 
`luaotfload-tool --find=arial` I get a lua-error (you can use the newest branch 2.9707-2019-05-18 for tests).

~~~~
C:\texlive\2019\bin\win32\runscript.tlu:922: ...load/texmf/tex/luatex/luaotfload/luaotfload-features.lua:204: bad argument #1 to 'for iterator' (table expected, got nil)
~~~~

A bit digging showed that in this case the `otf.tables` doesn't contain scripts or languages, only  ["featuretypes"]. 

~~~~
if scripts then
local verbosescripts   = swapped(scripts  )
end
if languages then
local verboselanguages = swapped(languages)
end
~~~~

avoids the error, but do this tables need some better defaults here?

**Comment by u-fischer** [comment]
@zauguin  perhaps related: while trying `luaotfload-tool --find=notosanscjkkr-regular --inspect` from PR #58 I got an error too (with a 64 bit texlive).

~~~
== 1.2 Features ================================================================C:\texlive\2019\bin-exp\win64\runscript.tlu:922: ...e/2019/texmf-dist/scripts/luaotfload/luaotfload-tool.lua:631: bad argument #1 to 'next' (table expected, got nil)
~~~

**Comment by zauguin** [comment]
@u-fischer Putting `if`s there breaks normal font loading because than the tables are `local` to the `if` block... Anyway, we can just load the tables than the error is fixed.

I can't reproduce the second problem.

**Pull request closed without merging**
