### PR TITLE
[DNM] Fix fontloader '---' bug

### LINKED ISSUE #44: tlig em dash ligature is broken
(moved from dev-luatex)

`---` doesn't give an em-dash if there are no spaces around it (but curriously a hyphen before change this). 

context doesn't have a problem. The problem is still there in the newest branch (v2.9603-...). 
It works with texlive2017 (and the same fontloader), which seems to imply some engine change but older cache content could play a role here too.

~~~~

\input luaotfload.sty
\font\test={name:texgyreheros:+tlig;}\test

em dashes---these % gives en-dash

em-dashes---these % gives em-dash

en dash--these %ok

\bye

~~~~

image

### PR DESCRIPTION
**Pull request by zauguin**
Fixes #44.
I posted this patch to the ConTeXt mailing list, so I copied it here for reference only.

### CODE REVIEW

**Comment by u-fischer** [comment]
Ah, good. I don't see the message on the context list(s) yet, but I guess it will appear in due time.

**Comment by zauguin** [comment]
@u-fischer It's pending "moderator approval"... If you are subscribed there, feel free to send the patch yourself, that might be easier.

**Comment by u-fischer** [comment]
Which list did you use? context or context-dev? (I can post to context, but a message to context-dev will probably end in the gmane-nirwana.)

**Comment by zauguin** [comment]
@u-fischer I tried to answer to your thread in the (non-dev) context list.

**Comment by zauguin** [comment]
@u-fischer This has been merged into ConTeXt, so it will be part of the next fontloader pull.

**Pull request closed without merging**
